name: Settings verification
on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Build and release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install the dependencies
        run: npm i
      
      - name: Verify missing settings
        run: node scripts/verify-settings.js ${{ github.ref }}

